### ISSUE TITLE
Zbudowanie aplikacji na urządzenie

### ISSUE THREAD

**Issue by owlcode** [wutee/propsy-mobile-client#1]

**Comment by owlcode** [comment]
@churskir chcesz się zmierzyć w pojedynkę? :)

**Comment by churskir** [comment]
Mogę, chociaż z @achellko zakładaliśmy że dodajemy to razem. Jak rozumiem to na najbliższy poniedziałek, tak?
To ma być dodane i do Sklepu Play i do AppStore czy tylko do jednego? I jak wygląda kwestia pokrycia kosztów? ($25 za Sklep Play i $99 za App Store).

**Comment by owlcode** [comment]
W takim razie nie publikujemy, trzeba tylko spróbować zrobić builda

**Comment by churskir** [comment]
Mogę zająć się Androidem.

**Comment by churskir** [comment]
Zrobione: https://github.com/wutee/readme/wiki/Uruchamianie-w-Android-Studio
