### ISSUE TITLE
[8] Krok wpisywania danych

### ISSUE THREAD

**Issue by owlcode** [wutee/propsy-mobile-client#16]
##  Widok + Kontroler

Formularz wprowadzania danych koniecznych do sfinalizowania zamówienia. Bez wyboru metody płatności - tylko dane, adres itp. Pola jak w bazie w tabeli `Orders` z uwzględnieniem dołączonych pól przez `FK`

Wszystkie pola wymagane

**Comment by achellko** [comment]
Scenariusz do testowania formularza:
PRE: Użytkownik znajduje się na stronie zamówienia
1. Użytkownik wypełnia wszystkie pola formularza
2. Użytkownik naciska przycisk "Submit"

Scenariusz do testowania zmiany języka:
PRE: Użytkownik znajduje się na stronie zamówienia
1. Użytkownik naciska na przełącznik językowy na dole strony 
2. Użytkownik wybiera dowolny język
3. System zmienia nazwę pol zgodnie z wybranym poprzez Użytkownika językiem

**Comment by achellko** [comment]
DEV 5
