### ISSUE TITLE
[13] Wyświetlenie dań dostępnych w wybranej sieci restauracji

### ISSUE THREAD

**Issue by yamatano18** [wutee/propsy-mobile-client#3]
Klient widzi listę wszystkich dań dostępnych w danej restauracji. Na każdym z dań jest guzik "dodaj do koszyka". Po kliknieciu guzika zostaje zawołana mockowa metoda `addToBasket(food)`

### Scenariusz główny
1. Aplikacja wyświetla dania dla wybranego menu restauracji
2. Aplikacja pozwala na dodawanie i usuwanie dań z koszyka

**Comment by msparrowskyIT** [comment]
Pierwsza wersja taska. Niestety dużo zastrzeżeń do xmysql, który wykorzystujemy do RestApi.

1. niestebilna praca (identyczny request raz zwraca 500 raz jest ok).
2. w moim przypadku nie mogłem uruchomić dynamic query. To sprawia, że zrobienie joina przez kilka tabeli jest bardzo nieczytelne.
3. Co gorsza, serwer zwraca model z suffixem, który stanowił alias w query. To nie pozwala wykorzystywać globalnie modelu.

![zrzut ekranu z 2018-10-29 00-40-04](https://user-images.githubusercontent.com/44372651/47623549-3e3f5680-db13-11e8-8339-574679b47729.png)

**Comment by msparrowskyIT** [comment]
I jeszcze pozostaje problem z CORS. Nie wiem czy można wyłączyć security z poziomu Angulara. Jeśli nie to pozostaje nam jakieś proxy pomiędzy xmsql, a aplikacją?

**Comment by owlcode** [comment]
Co myślisz o zrealizowaniu poszczególnych menu w restauracji jako zakładki, nie jako akordeon? Dodatkowo mogłyby być domyślnie rozwinięte (i tak nie mamy zbyt wiele danych).

Jak można programowo wyświetlić tą stronę dla restauracji o danym id?

**Comment by yamatano18** [comment]
Po dzisiejszych zajęciach trzeba podpiąć te produkty do określonego menu z wybranej restauracji

**Comment by owlcode** [comment]
Czy tutaj przypadkiem dalej nie mamy buga że każda restauracja wyświetla to samo? @yamatano18 @Fiszcz @msparrowskyIT  ?

**Comment by yamatano18** [comment]
Tutaj z Listy Restauracji zawsze jest podawane ID = 1
@trzaskom @scresh 
Do poprawki
