### ISSUE TITLE
[20] Koszyk Challenge

### ISSUE THREAD

**Issue by yamatano18** [wutee/propsy-mobile-client#4]
- dodawanie różnych dań z restauracji do koszyka
 - koszyk zapisywany w localStorage
 - template guzika FAB oraz propozycja wyglądu koszyka https://ionicframework.com/docs/components/#fabs

- podsumowanie ceny
- usuwanie z koszyka

### 1
1. Stan początkowy: Koszyk pusty
2. Kroki: Użytkownik dodaje kilka dań do koszyka
3. Stan końcowy: Wszystkie dania są w koszyku. Cena ogólna zgadza się z sumą produktów
### 2
1. Stan początkowy: Koszyk pełny
2. Kroki: Użytkownik usuwa dania z koszyka
3. Stan końcowy: Usunięte dania znikają z koszyka. Cena zostaje zaktualizowana.
### 3
1. Stan początkowy: Koszyk pełny
2. Kroki: Użytkownik włącza i wyłącza aplikację
3. Stan końcowy: Koszyk wygląda jak przed restartem

**Comment by owlcode** [comment]
@Fiszcz Jeżeli koszyk przechodzi scenariusze testowe które tam dopisałem to proszę zamknij to zadanie.
