### ISSUE TITLE
Krok wyboru metody płatności

### ISSUE THREAD

**Issue by yamatano18** [wutee/propsy-mobile-client#6]
- działa razem z resztą procesowania obiektu zamówienia
 - pobieranie listy dostępnych płatności
 - wyświetlanie listy dostępnych płatności
 - wybór
 - OK, idziemy dalej (bez żadnej integracji, zakładamy że wszystkie opcje dzialaja tak samo)

**Comment by yamatano18** [comment]
Zamawiający może zapłacić z góry lub wykorzystać punkty lojalnościowe.

**Comment by owlcode** [comment]
Punkty lojalnościowe są poza naszą uwagą. Możemy pokazać taki sposób płatności, ale nie wykonujemy żadnych specjalnych akcji w związku z nim.
