### ISSUE TITLE
[20] Widok - Lista zamówień

### ISSUE THREAD

**Issue by yamatano18** [wutee/propsy-mobile-client#9]
**Widok** dla listy zamówień. 
**Kontroler** prosty, tylko wystawione metody / dane zamockowane lub nie

Nazwy pól jak w bazie danych, płaska struktura JSONa, z uwzględnieniem dojoinowanych tabel po Foregin Key.

Każdy element listy ma mieć przypisane hooki / guziki / context menu / cokolwiek - w zależności od developera, które będzie pozwalało użytkownikowi na wykonanie _wszystkich_ wymaganych akcji tj.

 - pozwalać klientowi na ocenianie realizacji zamówienia.
 - pozwalać na zgłoszenie reklamacji.
 - pozwalać klientowi na weryfikację stanu zamówienia.
 - pozwalać klientowi na ponowienie zamówienia (mock)

Sugeruję zainteresować się tym:

https://github.com/ionic-team/ionic-preview-app/tree/master/src/pages/lists/sliding

https://ionicframework.com/docs/components/#multiline-list

### Scenariusz alternatywny
1. Aplikacja wyświetla informację o nie dokonaniu żadnych zamówień

**Comment by owlcode** [comment]
Rozumiem ze widok jest skończony ale na mockowych danych? Czy ktoś pracuje nad podłączeniem tego do bazy? @scresh
